sudo: false

language: node_js

node_js:
  - "4"
  - "6"

service_name: travis-ci
repo_token: KbtOD5oIWVEWucmwGLFlBPUvu40uoejEp
  
 
env:
  global:
    - NODE_ENV=travisci
    - NPM_CONFIG_PROGRESS="false"

before_install:
  - npm install

script:  npm test


after_script:
    - npm run coveralls
